import React from "react";
import NavBar from "./NavBar";
import Head from "next/head";
import Contacts from "./Contacts";
import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NavBar />
      <div className="min-h-[50vh]">{children}</div>
      <Contacts />
      <Footer />
    </div>
  );
}

export default Layout;
